site_name: Data Safe Haven Cluster Services
site_description: Documentation for using the DSH cluster
site_url: https://github-pages.arc.ucl.ac.uk/mkdocs-dsh-docs/
theme:
  name: material
  logo: images/icon-ucl-logo.png
  features:
    #- navigation.tabs #turning off tabs (can be turned on later)
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
      primary: amber
      accent: yellow 
    - scheme: slate 
      toggle:
        icon: material/eye-outline
        name: Switch to light mode    
      primary: amber 
      accent: yellow
  extra_css:
  - 'stylesheets/style.css'   

markdown_extensions:
  - admonition
  - footnotes
  - attr_list

plugins:
  - search
  - awesome-nav:
      strict: false
      collapse_single_pages: true
      title_case: true

