site_name: Data Safe Haven Cluster Services Documentation
site_description: Documentation for using the DSH cluster
site_url: https://github-pages.arc.ucl.ac.uk/mkdocs-dsh-docs/
theme:
  name: material
  logo: images/icon-ucl-logo.png
  custom_dir: overrides
  repo_url: https://github.com/UCL-ARC/mkdocs-dsh-docs
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
      primary: custom
      accent: pink
    - scheme: slate 
      toggle:
        icon: material/eye-outline
        name: Switch to light mode    
      primary: custom
      accent: pink  
repo_url: 
extra:
  homepage: https://www.ucl.ac.uk
  social:
    - icon: fontawesome/brands/github
    - link: https://github.com/squidfunk/mkdocs-material   
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- Thanks for your feedback!  
extra_css:
  - 'stylesheets/style.css'   

markdown_extensions:
  - admonition
  - footnotes
  - attr_list

plugins:
  - search
  - awesome-nav:
      strict: false
      collapse_single_pages: true
      title_case: true
      ignore_files:
        - 'index.md'
copyright: Copyright &copy; 2022 Bespoke Solutions Teams, UCL
